# Generated by Django 5.0.6 on 2024-07-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="title",
        ),
    ]
