# Generated by Django 5.0.6 on 2024-09-19 22:45

import config.yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_is_celebretie_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(storage=config.yandex_s3_storage.ClientDocsStorage(), upload_to='category_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.yandex_s3_storage.ClientDocsStorage(), upload_to='course_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='module',
            name='data',
            field=models.FileField(blank=True, null=True, storage=config.yandex_s3_storage.ClientDocsStorage(), upload_to='module_data', verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.yandex_s3_storage.ClientDocsStorage(), upload_to='course_images', verbose_name='Изображение'),
        ),
    ]
