# Generated by Django 5.0.6 on 2024-10-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_is_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['index'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AddField(
            model_name='module',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Индекс'),
            preserve_default=False,
        ),
    ]
