# Generated by Django 5.0.6 on 2024-08-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
    ]
