# Generated by Django 5.0.6 on 2024-09-18 08:31

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Кошелек', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
        migrations.CreateModel(
            name='RequestFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, help_text='Введите номер карты', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Введите номер карты в формате: 'XXXX XXXX XXXX XXXX' или 'XXXX XXXX XXXX XXXX XXX'", regex='^\\d{4}(?:\\s\\d{4}){2,4}$')], verbose_name='Номер карты')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+7 (123) 123-45-67', max_length=128, null=True, region='RU', unique=True, verbose_name='phone number')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('In process', 'В процессе'), ('Completed', 'Завершено')], max_length=10, verbose_name='status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_request', to=settings.AUTH_USER_MODEL, verbose_name='Запрос на получение')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
    ]
