# Generated by Django 5.0.6 on 2024-07-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.IntegerField(verbose_name="Рост в см."),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.IntegerField(verbose_name="Вес в кг."),
        ),
    ]
