# Generated by Django 5.0.6 on 2024-07-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_number_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number",
            field=models.IntegerField(verbose_name="Номер телефона"),
        ),
    ]
