# Generated by Django 5.0.6 on 2024-07-15 00:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of Birth"),
        ),
        migrations.AlterField(
            model_name="user",
            name="desc",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first_name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Муж."), ("F", "Жен.")],
                max_length=1,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="height in centimeters"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/pngegg.png",
                null=True,
                upload_to="avatars/",
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_coach",
            field=models.BooleanField(default=False, verbose_name="is_coach"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last_name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BEG", "Beginner"),
                    ("MID", "Midlle"),
                    ("ADV", "Advanced"),
                    ("PRO", "Professional"),
                ],
                max_length=3,
                null=True,
                verbose_name="level",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="+7 (123) 123-45-67",
                max_length=128,
                null=True,
                region="RU",
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LW", "Lose_weight"),
                    ("GW", "Gain_weight"),
                    ("HL", "Health"),
                    ("OT", "Other"),
                ],
                max_length=2,
                null=True,
                verbose_name="target",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="height in kilograms"
            ),
        ),
    ]
